### PR TITLE
[TOOLS-1624] Allow a user to define an output file for HDRHistogram data in asbenchmark

### PR DESCRIPTION
**Pull request by ClaytonKnittel**
Added the --hdrHist flag, which specifies the directory to dump hdrHist output files to. Had to bring in some more components of the hdr hist from the memtier benchmark (hdr_histogram_log, hdr_time, and hdr_encoding). Also cleaned up some code a bit and added more tests.

### CODE REVIEW

**Comment by ClaytonKnittel** [comment]
Doesn't need to be merged immediately, I haven't fully finished the TOOLS-1624 ticket, but it has almost all the functionality (still need to output histogram data to a .txt file in addition to the .hdrhist files that are being outputted now, since you can't decode the .hdrhist files easily yet)

**Comment by ClaytonKnittel** [comment]
Ok this should be ready for review now. The [TOOLS-1624] ticket is done

**Review by arrowplum — APPROVED** [review]
Looks good to me. I appreciate the negative testing too. @marknaero We have spoken about this project but see here.

**Comment by arrowplum** [comment]
I still think we are for some reason repeating commit messages. Try deleting your fork possibly.

**Pull request merged**
