### PR TITLE
Fixed GitHub Actions cache bug

### PR DESCRIPTION
**Pull request by ClaytonKnittel**
Removed the line from the clear temp directories step which deletes libcheck, since the cache-saving step happens after everything else. Also added the OS type to the cache key (so it will rebuild for different OS's).

### CODE REVIEW

**Review by arrowplum — APPROVED** [review]
I got some sort of deja vu here with the commit messages but the diffs look fine. thank you for the actions fixes.

**Comment by arrowplum** [comment]
Codecov complaining about a .03% decrease in coverage seems overly harsh.

**Comment by ClaytonKnittel** [comment]
Yeah not sure what the duplicate diffs are for, I thought last PR was already approved.

**Comment by arrowplum** [comment]
it was. maybe needed to pull first?

**Comment by arrowplum** [comment]
or pull then push

**Comment by ClaytonKnittel** [comment]
I see, rebasing is always annoying since I have to go through each commit and resolve merge conflicts, though I may be doing it wrong

**Comment by ClaytonKnittel** [comment]
Also next PR should see an increase in code coverage

**Pull request merged**
